### PR TITLE
Fixed to now work with PHP 5.4

### PR DESCRIPTION
**Pull request by AJ-Acevedo**
This has been tested to work on WordPress 3.5.2
As well as PHP 5.2 - 5.4
I'll test with WP 3.6.1 when I get a chance.
    modified:   instapress/instagram.php
    modified:   instapress/widget.php

### CODE REVIEW

**Comment by Liechtenecker** [comment]
Reviewed the code and tested it with WP (3.2.1)

Plugin installation is now working - no Fatal Errors thrown.

Thank you AJ!

**Comment by AJ-Acevedo** [comment]
No problem!

**Comment by timvanrooyen** [comment]
Eagerly awaiting the paging to be fixed. 

Also results when specifying userid="igname" and tag="igtag" are not yielding the expected results. I'm getting far fewer images than expected.

**Comment by AJ-Acevedo** [comment]
@timvanrooyen it's usually a good idea to open an Issue on the project's repo with a specific description of the issue and your expected behavior.

**Pull request merged**
